### ISSUE TITLE
Update the list with Software Engineers

### ISSUE THREAD

**Issue by bensonOSei** [mesrenyamedogbe/made-in-ghana#30]
I realized the list does not contain names of SWEs. It could be Web development, or mobile app development, or probably both

**Comment by bensonOSei** [comment]
> I realized the list does not contain names of SWEs. It could be Web development, or mobile app development, or probably both
#31 Created a pull request to solve this. Check it @mesrenyamedogbe

**Comment by mesrenyamedogbe** [comment]
Hello Ben, thanks for raising this issue. I have started a list for Web developers and mobile app developers. Kindly check it out and contribute as well. Thank you and I appreciate it.

**Comment by bensonOSei** [comment]
> Hello Ben, thanks for raising this issue. I have started a list for Web developers and mobile app developers. Kindly check it out and contribute as well. Thank you and I appreciate it.

That's great! I'll do that
